/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jgrzegulski' at '29.09.16 10:55' with Gradle 2.6
 *
 * @author jgrzegulski, @date 29.09.16 10:55
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
