/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jgrzegulski' at '27.09.16 11:35' with Gradle 2.6
 *
 * @author jgrzegulski, @date 27.09.16 11:35
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
